# Kaggle Dataset

Clean kaggle dataset by removing unnecessary columns making it fatser to load and cleaner to look at

In [4]:
import pandas as pd
import numpy as np

In [5]:
df_kaggle = pd.read_csv("data/US_AQI.csv", index_col=0)
df_kaggle.head()

,CBSA Code,Date,AQI,Category,Defining Parameter,Number of Sites Reporting,city_ascii,state_id,state_name,lat,lng,population,density,timezone
0,10140,2022-01-01,21,Good,PM2.5,2,Aberdeen,WA,Washington,46.9757,-123.8094,16571.0,588.0,America/Los_Angeles
1,10140,2022-01-02,12,Good,PM2.5,2,Aberdeen,WA,Washington,46.9757,-123.8094,16571.0,588.0,America/Los_Angeles
2,10140,2022-01-03,18,Good,PM2.5,2,Aberdeen,WA,Washington,46.9757,-123.8094,16571.0,588.0,America/Los_Angeles
3,10140,2022-01-04,19,Good,PM2.5,2,Aberdeen,WA,Washington,46.9757,-123.8094,16571.0,588.0,America/Los_Angeles
4,10140,2022-01-05,17,Good,PM2.5,2,Aberdeen,WA,Washington,46.9757,-123.8094,16571.0,588.0,America/Los_Angeles

In [6]:
df_kaggle.dtypes

CBSA Code                      int64
Date                          object
AQI                            int64
Category                      object
Defining Parameter            object
Number of Sites Reporting      int64
city_ascii                    object
state_id                      object
state_name                    object
lat                          float64
lng                          float64
population                   float64
density                      float64
timezone                      object
dtype: object

In [7]:
df_kaggle["Defining Parameter"].unique()

array(['PM2.5', 'Ozone', 'NO2', 'PM10', 'CO'], dtype=object)

In [8]:
df_new = df_kaggle[["CBSA Code", "Date", "AQI", "Category", "Defining Parameter", "state_name", "lat", "lng", "population", "density"]]
df_new.head()

,CBSA Code,Date,AQI,Category,Defining Parameter,state_name,lat,lng,population,density
0,10140,2022-01-01,21,Good,PM2.5,Washington,46.9757,-123.8094,16571.0,588.0
1,10140,2022-01-02,12,Good,PM2.5,Washington,46.9757,-123.8094,16571.0,588.0
2,10140,2022-01-03,18,Good,PM2.5,Washington,46.9757,-123.8094,16571.0,588.0
3,10140,2022-01-04,19,Good,PM2.5,Washington,46.9757,-123.8094,16571.0,588.0
4,10140,2022-01-05,17,Good,PM2.5,Washington,46.9757,-123.8094,16571.0,588.0

In [9]:
df_new.to_csv("./data/kaggle_cleaned.csv")
# To load: df_kaggle = pd.read_csv("./data/kaggle_cleaned.csv", index_col=0)